name: flutter_fish_redux_router_qt
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 状态管理
  fish_redux: ^0.3.1
  # 网络请求库
  dio: ^3.0.9
  # 获取APP版本号
  package_info: ^0.4.0+14
  # 时间格式化
  date_format: ^1.0.8
  # 数据持久化，类似于nsuserdefault
  shared_preferences: ^0.5.6+3
  # 图片缓存
  cached_network_image: ^2.0.0
  # 轮播图
  flutter_swiper: ^1.1.6
  # 加载web页面
  webview_flutter: ^0.3.19+9
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/Bitmap.webp
    - images/2.0x/Bitmap.webp
    - images/3.0x/Bitmap.webp
    - images/customer.webp
    - images/2.0x/customer.webp
    - images/3.0x/customer.webp
    - images/home.webp
    - images/2.0x/home.webp
    - images/3.0x/home.webp
    - images/my.webp
    - images/2.0x/my.webp
    - images/3.0x/my.webp
    - images/customer_select.webp
    - images/2.0x/customer_select.webp
    - images/3.0x/customer_select.webp
    - images/home_select.webp
    - images/2.0x/home_select.webp
    - images/3.0x/home_select.webp
    - images/my_select.webp
    - images/2.0x/my_select.webp
    - images/3.0x/my_select.webp
    - images/loginback.png
    - images/2.0x/loginback.png
    - images/3.0x/loginback.png

    - images/jump_arrow.webp
    - images/2.0x/jump_arrow.webp
    - images/3.0x/jump_arrow.webp
    - images/login_input_background.webp
    - images/2.0x/login_input_background.webp
    - images/3.0x/login_input_background.webp
    - images/login_phone_icon.webp
    - images/2.0x/login_phone_icon.webp
    - images/3.0x/login_phone_icon.webp
    - images/password_icon.webp
    - images/2.0x/password_icon.webp
    - images/3.0x/password_icon.webp
    - images/ycf_logo.webp
    - images/2.0x/ycf_logo.webp
    - images/3.0x/ycf_logo.webp
    - images/password_show_icon.webp
    - images/2.0x/password_show_icon.webp
    - images/3.0x/password_show_icon.webp
    - images/password_hidden_icon.webp
    - images/2.0x/password_hidden_icon.webp
    - images/3.0x/password_hidden_icon.webp

    - images/company_icon.webp
    - images/2.0x/company_icon.webp
    - images/3.0x/company_icon.webp
    - images/normal_vip.webp
    - images/2.0x/normal_vip.webp
    - images/3.0x/normal_vip.webp
    - images/header_photo.webp
    - images/2.0x/header_photo.webp
    - images/3.0x/header_photo.webp
    - images/persion_set.webp
    - images/2.0x/persion_set.webp
    - images/3.0x/persion_set.webp
    - images/persion_message.webp
    - images/2.0x/persion_message.webp
    - images/3.0x/persion_message.webp
    - images/info_descbgimage.webp
    - images/2.0x/info_descbgimage.webp
    - images/3.0x/info_descbgimage.webp
    - images/nav_backgroundimage.webp
    - images/2.0x/nav_backgroundimage.webp
    - images/3.0x/nav_backgroundimage.webp

    - images/order_icon0.webp
    - images/2.0x/order_icon0.webp
    - images/3.0x/order_icon0.webp
    - images/order_icon1.webp
    - images/2.0x/order_icon1.webp
    - images/3.0x/order_icon1.webp
    - images/order_icon2.webp
    - images/2.0x/order_icon2.webp
    - images/3.0x/order_icon2.webp
    - images/order_icon3.webp
    - images/2.0x/order_icon3.webp
    - images/3.0x/order_icon3.webp
    - images/order_icon4.webp
    - images/2.0x/order_icon4.webp
    - images/3.0x/order_icon4.webp
    - images/order_icon5.webp
    - images/2.0x/order_icon5.webp
    - images/3.0x/order_icon5.webp
    - images/order_icon6.webp
    - images/2.0x/order_icon6.webp
    - images/3.0x/order_icon6.webp
    - images/order_icon7.webp
    - images/2.0x/order_icon7.webp
    - images/3.0x/order_icon7.webp
    - images/order_icon8.webp
    - images/2.0x/order_icon8.webp
    - images/3.0x/order_icon8.webp
    - images/order_icon9.webp
    - images/2.0x/order_icon9.webp
    - images/3.0x/order_icon9.webp

    - images/menu_icon0.webp
    - images/2.0x/menu_icon0.webp
    - images/3.0x/menu_icon0.webp
    - images/menu_icon1.webp
    - images/2.0x/menu_icon1.webp
    - images/3.0x/menu_icon1.webp
    - images/menu_icon2.webp
    - images/2.0x/menu_icon2.webp
    - images/3.0x/menu_icon2.webp
    - images/menu_icon3.webp
    - images/2.0x/menu_icon3.webp
    - images/3.0x/menu_icon3.webp
    - images/menu_icon4.webp
    - images/2.0x/menu_icon4.webp
    - images/3.0x/menu_icon4.webp
    - images/menu_icon5.webp
    - images/2.0x/menu_icon5.webp
    - images/3.0x/menu_icon5.webp
    - images/menu_icon6.webp
    - images/2.0x/menu_icon6.webp
    - images/3.0x/menu_icon6.webp
    - images/menu_icon7.webp
    - images/2.0x/menu_icon7.webp
    - images/3.0x/menu_icon7.webp

    - images/nomal_icon0.webp
    - images/2.0x/nomal_icon0.webp
    - images/3.0x/nomal_icon0.webp
    - images/nomal_icon1.webp
    - images/2.0x/nomal_icon1.webp
    - images/3.0x/nomal_icon1.webp
    - images/nomal_icon2.webp
    - images/2.0x/nomal_icon2.webp
    - images/3.0x/nomal_icon2.webp
    - images/nomal_icon3.webp
    - images/2.0x/nomal_icon3.webp
    - images/3.0x/nomal_icon3.webp
    - images/nomal_icon4.webp
    - images/2.0x/nomal_icon4.webp
    - images/3.0x/nomal_icon4.webp

    - images/nomal_arrow.webp
    - images/2.0x/nomal_arrow.webp
    - images/3.0x/nomal_arrow.webp
    - images/splash.png
    - images/2.0x/splash.png
    - images/3.0x/splash.png

    - images/message_icon.webp
    - images/2.0x/message_icon.webp
    - images/3.0x/message_icon.webp
    - images/addpersion_icon.webp
    - images/2.0x/addpersion_icon.webp
    - images/3.0x/addpersion_icon.webp

    - images/search_icon.webp
    - images/2.0x/search_icon.webp
    - images/3.0x/search_icon.webp
    - images/close_icon.webp
    - images/2.0x/close_icon.webp
    - images/3.0x/close_icon.webp

    - images/filter_icon.webp
    - images/2.0x/filter_icon.webp
    - images/3.0x/filter_icon.webp

    - images/select_filter_btn.webp
    - images/2.0x/select_filter_btn.webp
    - images/3.0x/select_filter_btn.webp

    - images/arrow_bottom.webp
    - images/2.0x/arrow_bottom.webp
    - images/3.0x/arrow_bottom.webp
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
