import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/material.dart' hide Action;
import 'package:flutter_fish_redux_router_qt/models/cjzblist.dart';
import 'package:flutter_fish_redux_router_qt/network/api.dart';
import 'package:flutter_fish_redux_router_qt/network/request.dart';
import 'action.dart';
import 'components/state.dart';

import 'state.dart';

Effect<CjzbState> buildEffect() {
  return combineEffects(<Object, Effect<CjzbState>>{
    CjzbAction.action: _onAction,
    CjzbAction.onjumpDetail: _onJumpDetail,
    Lifecycle.initState:_onInit
  });
}

void _onAction(Action action, Context<CjzbState> ctx) {
}
void _onJumpDetail(Action action,Context<CjzbState> ctx) {
  Navigator.pushNamed(ctx.context, 'cjzbdetail').then((value){
    ctx.dispatch(CjzbActionCreator.onUpdateData(value));
  });
}
void _onInit(Action action,Context<CjzbState> ctx) {
    _loadData(ctx);
}
//获取财经早报的列表数据
_loadData(Context<CjzbState> ctx){
  List<LocalNavList> subjects = [];

  List<CjcellState> cjcellstatelist = [];
  Request.getInstance().get(API.kBillboardlistUrl, null,null, (value){
  Autogenerated model =  Autogenerated.fromJson(value);
  subjects = model.localNavList;
  subjects.forEach((model){
    print('value:'+ model.title);
    CjcellState cjcellState = CjcellState();
    cjcellState.celltitle = model.title;
    cjcellState.cellcontent = '3/19·132阅读·预计阅读：6分钟';
    cjcellState.cellcoverimagename = 'images/Bitmap.webp';
    cjcellstatelist.add(cjcellState);
  });
//      发送事件更新UI界面
    ctx.dispatch(CjzbActionCreator.onInit(cjcellstatelist));
  }, (error){

  });
}